//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Test.ServiceInvoice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTODocumentoEntrada", Namespace="http://schemas.datacontract.org/2004/07/Facturacion.Entity")]
    [System.SerializableAttribute()]
    public partial class DTODocumentoEntrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Facturacion.Test.ServiceInvoice.DTOClienteEntrada ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoNotaCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoNotaDebitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiasVenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoFacturaReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Facturacion.Test.ServiceInvoice.DTOImpuestosEntrada[] ImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PorInteresMoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Facturacion.Test.ServiceInvoice.DTOReferenciasEntrada[] ReferenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrNetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrSubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Facturacion.Test.ServiceInvoice.DTOClienteEntrada Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConceptoNotaCredito {
            get {
                return this.ConceptoNotaCreditoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoNotaCreditoField, value) != true)) {
                    this.ConceptoNotaCreditoField = value;
                    this.RaisePropertyChanged("ConceptoNotaCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConceptoNotaDebito {
            get {
                return this.ConceptoNotaDebitoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoNotaDebitoField, value) != true)) {
                    this.ConceptoNotaDebitoField = value;
                    this.RaisePropertyChanged("ConceptoNotaDebito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiasVence {
            get {
                return this.DiasVenceField;
            }
            set {
                if ((this.DiasVenceField.Equals(value) != true)) {
                    this.DiasVenceField = value;
                    this.RaisePropertyChanged("DiasVence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoFacturaReferencia {
            get {
                return this.DocumentoFacturaReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoFacturaReferenciaField, value) != true)) {
                    this.DocumentoFacturaReferenciaField = value;
                    this.RaisePropertyChanged("DocumentoFacturaReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((this.HoraField.Equals(value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Facturacion.Test.ServiceInvoice.DTOImpuestosEntrada[] Impuestos {
            get {
                return this.ImpuestosField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpuestosField, value) != true)) {
                    this.ImpuestosField = value;
                    this.RaisePropertyChanged("Impuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedioPago {
            get {
                return this.MedioPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedioPagoField, value) != true)) {
                    this.MedioPagoField = value;
                    this.RaisePropertyChanged("MedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.NotaField, value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PorInteresMora {
            get {
                return this.PorInteresMoraField;
            }
            set {
                if ((this.PorInteresMoraField.Equals(value) != true)) {
                    this.PorInteresMoraField = value;
                    this.RaisePropertyChanged("PorInteresMora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Facturacion.Test.ServiceInvoice.DTOReferenciasEntrada[] Referencias {
            get {
                return this.ReferenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciasField, value) != true)) {
                    this.ReferenciasField = value;
                    this.RaisePropertyChanged("Referencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resolucion {
            get {
                return this.ResolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolucionField, value) != true)) {
                    this.ResolucionField = value;
                    this.RaisePropertyChanged("Resolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoElectronico {
            get {
                return this.TipoDocumentoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoElectronicoField, value) != true)) {
                    this.TipoDocumentoElectronicoField = value;
                    this.RaisePropertyChanged("TipoDocumentoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrDescuento {
            get {
                return this.VlrDescuentoField;
            }
            set {
                if ((this.VlrDescuentoField.Equals(value) != true)) {
                    this.VlrDescuentoField = value;
                    this.RaisePropertyChanged("VlrDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrImpuestos {
            get {
                return this.VlrImpuestosField;
            }
            set {
                if ((this.VlrImpuestosField.Equals(value) != true)) {
                    this.VlrImpuestosField = value;
                    this.RaisePropertyChanged("VlrImpuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrNeto {
            get {
                return this.VlrNetoField;
            }
            set {
                if ((this.VlrNetoField.Equals(value) != true)) {
                    this.VlrNetoField = value;
                    this.RaisePropertyChanged("VlrNeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrSubtotal {
            get {
                return this.VlrSubtotalField;
            }
            set {
                if ((this.VlrSubtotalField.Equals(value) != true)) {
                    this.VlrSubtotalField = value;
                    this.RaisePropertyChanged("VlrSubtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOClienteEntrada", Namespace="http://schemas.datacontract.org/2004/07/Facturacion.Entity")]
    [System.SerializableAttribute()]
    public partial class DTOClienteEntrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ObligadoFacturarElectroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRegimenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoCliente {
            get {
                return this.DocumentoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoClienteField, value) != true)) {
                    this.DocumentoClienteField = value;
                    this.RaisePropertyChanged("DocumentoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ObligadoFacturarElectro {
            get {
                return this.ObligadoFacturarElectroField;
            }
            set {
                if ((this.ObligadoFacturarElectroField.Equals(value) != true)) {
                    this.ObligadoFacturarElectroField = value;
                    this.RaisePropertyChanged("ObligadoFacturarElectro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombre {
            get {
                return this.PrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreField, value) != true)) {
                    this.PrimerNombreField = value;
                    this.RaisePropertyChanged("PrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombre {
            get {
                return this.SegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreField, value) != true)) {
                    this.SegundoNombreField = value;
                    this.RaisePropertyChanged("SegundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoCliente {
            get {
                return this.TipoDocumentoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoClienteField, value) != true)) {
                    this.TipoDocumentoClienteField = value;
                    this.RaisePropertyChanged("TipoDocumentoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPersona {
            get {
                return this.TipoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPersonaField, value) != true)) {
                    this.TipoPersonaField = value;
                    this.RaisePropertyChanged("TipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRegimen {
            get {
                return this.TipoRegimenField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRegimenField, value) != true)) {
                    this.TipoRegimenField = value;
                    this.RaisePropertyChanged("TipoRegimen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOImpuestosEntrada", Namespace="http://schemas.datacontract.org/2004/07/Facturacion.Entity")]
    [System.SerializableAttribute()]
    public partial class DTOImpuestosEntrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PorTarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrImpuestoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PorTarifa {
            get {
                return this.PorTarifaField;
            }
            set {
                if ((this.PorTarifaField.Equals(value) != true)) {
                    this.PorTarifaField = value;
                    this.RaisePropertyChanged("PorTarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoImpuesto {
            get {
                return this.TipoImpuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoImpuestoField, value) != true)) {
                    this.TipoImpuestoField = value;
                    this.RaisePropertyChanged("TipoImpuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrBase {
            get {
                return this.VlrBaseField;
            }
            set {
                if ((this.VlrBaseField.Equals(value) != true)) {
                    this.VlrBaseField = value;
                    this.RaisePropertyChanged("VlrBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrImpuesto {
            get {
                return this.VlrImpuestoField;
            }
            set {
                if ((this.VlrImpuestoField.Equals(value) != true)) {
                    this.VlrImpuestoField = value;
                    this.RaisePropertyChanged("VlrImpuesto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOReferenciasEntrada", Namespace="http://schemas.datacontract.org/2004/07/Facturacion.Entity")]
    [System.SerializableAttribute()]
    public partial class DTOReferenciasEntrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PorDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VlrDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlrUnitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((this.IdentificadorField.Equals(value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PorDescuento {
            get {
                return this.PorDescuentoField;
            }
            set {
                if ((this.PorDescuentoField.Equals(value) != true)) {
                    this.PorDescuentoField = value;
                    this.RaisePropertyChanged("PorDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VlrDescuento {
            get {
                return this.VlrDescuentoField;
            }
            set {
                if ((this.VlrDescuentoField.Equals(value) != true)) {
                    this.VlrDescuentoField = value;
                    this.RaisePropertyChanged("VlrDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrTotal {
            get {
                return this.VlrTotalField;
            }
            set {
                if ((this.VlrTotalField.Equals(value) != true)) {
                    this.VlrTotalField = value;
                    this.RaisePropertyChanged("VlrTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlrUnitario {
            get {
                return this.VlrUnitarioField;
            }
            set {
                if ((this.VlrUnitarioField.Equals(value) != true)) {
                    this.VlrUnitarioField = value;
                    this.RaisePropertyChanged("VlrUnitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTODocumentoSalida", Namespace="http://schemas.datacontract.org/2004/07/Facturacion.Entity")]
    [System.SerializableAttribute()]
    public partial class DTODocumentoSalida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CufeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosQRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRespuestaField, value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cufe {
            get {
                return this.CufeField;
            }
            set {
                if ((object.ReferenceEquals(this.CufeField, value) != true)) {
                    this.CufeField = value;
                    this.RaisePropertyChanged("Cufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosQR {
            get {
                return this.DatosQRField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosQRField, value) != true)) {
                    this.DatosQRField = value;
                    this.RaisePropertyChanged("DatosQR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRespuesta {
            get {
                return this.DescripcionRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionRespuestaField, value) != true)) {
                    this.DescripcionRespuestaField = value;
                    this.RaisePropertyChanged("DescripcionRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalleRespuesta {
            get {
                return this.DetalleRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleRespuestaField, value) != true)) {
                    this.DetalleRespuestaField = value;
                    this.RaisePropertyChanged("DetalleRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((this.IdDocumentoField.Equals(value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nit {
            get {
                return this.NitField;
            }
            set {
                if ((object.ReferenceEquals(this.NitField, value) != true)) {
                    this.NitField = value;
                    this.RaisePropertyChanged("Nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInvoice.IServiceFacturacion")]
    public interface IServiceFacturacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFacturacion/RegistrarFactura", ReplyAction="http://tempuri.org/IServiceFacturacion/RegistrarFacturaResponse")]
        Facturacion.Test.ServiceInvoice.DTODocumentoSalida RegistrarFactura(string user, string Password, string TipoDocumentoEmpresa, string NitEmpresa, Facturacion.Test.ServiceInvoice.DTODocumentoEntrada entrada, string Origen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFacturacion/RegistrarFactura", ReplyAction="http://tempuri.org/IServiceFacturacion/RegistrarFacturaResponse")]
        System.Threading.Tasks.Task<Facturacion.Test.ServiceInvoice.DTODocumentoSalida> RegistrarFacturaAsync(string user, string Password, string TipoDocumentoEmpresa, string NitEmpresa, Facturacion.Test.ServiceInvoice.DTODocumentoEntrada entrada, string Origen);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFacturacionChannel : Facturacion.Test.ServiceInvoice.IServiceFacturacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFacturacionClient : System.ServiceModel.ClientBase<Facturacion.Test.ServiceInvoice.IServiceFacturacion>, Facturacion.Test.ServiceInvoice.IServiceFacturacion {
        
        public ServiceFacturacionClient() {
        }
        
        public ServiceFacturacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFacturacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFacturacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Facturacion.Test.ServiceInvoice.DTODocumentoSalida RegistrarFactura(string user, string Password, string TipoDocumentoEmpresa, string NitEmpresa, Facturacion.Test.ServiceInvoice.DTODocumentoEntrada entrada, string Origen) {
            return base.Channel.RegistrarFactura(user, Password, TipoDocumentoEmpresa, NitEmpresa, entrada, Origen);
        }
        
        public System.Threading.Tasks.Task<Facturacion.Test.ServiceInvoice.DTODocumentoSalida> RegistrarFacturaAsync(string user, string Password, string TipoDocumentoEmpresa, string NitEmpresa, Facturacion.Test.ServiceInvoice.DTODocumentoEntrada entrada, string Origen) {
            return base.Channel.RegistrarFacturaAsync(user, Password, TipoDocumentoEmpresa, NitEmpresa, entrada, Origen);
        }
    }
}
